export type TagEntry = {
  key: string;
  label: string;
  category: string;
  tutorial?: string;
  example?: string;
  aliases?: string[];
};

function slugify(value: string) {
  return value
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "");
}

export const WORLD_LANGUAGES = [
  "1C Enterprise",
  "ABAP",
  "ActionScript",
  "Ada",
  "Apex",
  "APL",
  "Arduino",
  "Assembly",
  "Astro",
  "AutoHotkey",
  "Ballerina",
  "Bash",
  "Batchfile",
  "Beef",
  "C",
  "C#",
  "C++",
  "Clojure",
  "COBOL",
  "CoffeeScript",
  "Crystal",
  "CSS",
  "Cue",
  "D",
  "Dart",
  "Delphi",
  "Dockerfile",
  "EJS",
  "Elixir",
  "Elm",
  "Erlang",
  "F#",
  "Fortran",
  "GDScript",
  "Gherkin",
  "GLSL",
  "Go",
  "GraphQL",
  "Groovy",
  "Hack",
  "Haskell",
  "Haxe",
  "HTML",
  "HCL",
  "IDL",
  "INI",
  "Java",
  "JavaScript",
  "Jinja",
  "Jinja2",
  "Julia",
  "Kotlin",
  "LaTeX",
  "Lisp",
  "LiveScript",
  "Lua",
  "Makefile",
  "Markdown",
  "MATLAB",
  "MDX",
  "Mermaid",
  "Nim",
  "Nix",
  "Objective-C",
  "OCaml",
  "Pascal",
  "Perl",
  "PHP",
  "PL/SQL",
  "PostCSS",
  "PowerShell",
  "Prisma",
  "Prolog",
  "Pug",
  "PureScript",
  "Python",
  "Q#",
  "R",
  "Racket",
  "Razor",
  "ReasonML",
  "Red",
  "RegEx",
  "ReScript",
  "Robot Framework",
  "Ruby",
  "Rust",
  "SAS",
  "Scala",
  "Scheme",
  "SCSS",
  "Shell",
  "Solidity",
  "SQL",
  "Squirrel",
  "Svelte",
  "Swift",
  "SystemVerilog",
  "Tcl",
  "Terraform",
  "Tex",
  "Toml",
  "TypeScript",
  "Typst",
  "VB.NET",
  "Verilog",
  "VHDL",
  "Vim Script",
  "Vue",
  "WebAssembly",
  "Wolfram",
  "XML",
  "XSLT",
  "YAML",
  "Zig",
  "React",
  "React Native",
  "Next.js",
  "Nuxt",
  "Node.js",
  "Express",
  "NestJS",
  "Fastify",
  "Deno",
  "Bun",
  "Angular",
  "Lit",
  "Alpine.js",
  "Tailwind CSS",
  "Bootstrap",
  "Chakra UI",
  "Shadcn UI",
  "Framer Motion",
  "Three.js",
  "Electron",
  "Tauri",
  "Flutter",
  "Unity C#",
  "Unreal C++",
  "Godot",
  "Pine Script",
  "NoSQL",
  "MongoDB",
  "PostgreSQL",
  "MySQL",
  "SQLite",
  "Redis",
  "Supabase",
  "Firebase",
  "ClickHouse",
  "BigQuery",
  "Snowflake",
  "KQL",
  "PromQL",
  "OpenAPI",
  "gRPC",
  "ProtoBuf",
  "AWS CDK",
  "CloudFormation",
  "Kubernetes",
  "Helm",
  "Ansible",
  "Puppet",
  "Chef",
  "Jest",
  "Vitest",
  "Playwright",
  "Cypress",
  "Selenium",
  "PyTest",
  "Mocha",
  "Storybook",
  "Figma Tokens",
  "AIDA",
  "PAS",
  "Storytelling",
  "Copywriting",
  "SEO"
];

const VOID_HTML_TAGS = new Set([
  "area",
  "base",
  "br",
  "col",
  "embed",
  "hr",
  "img",
  "input",
  "link",
  "meta",
  "source",
  "track",
  "wbr"
]);

const HTML_TAGS = [
  "a",
  "abbr",
  "address",
  "area",
  "article",
  "aside",
  "audio",
  "b",
  "base",
  "bdi",
  "bdo",
  "blockquote",
  "body",
  "br",
  "button",
  "canvas",
  "caption",
  "cite",
  "code",
  "col",
  "colgroup",
  "data",
  "datalist",
  "dd",
  "del",
  "details",
  "dfn",
  "dialog",
  "div",
  "dl",
  "dt",
  "em",
  "embed",
  "fieldset",
  "figcaption",
  "figure",
  "footer",
  "form",
  "h1",
  "h2",
  "h3",
  "h4",
  "h5",
  "h6",
  "head",
  "header",
  "hgroup",
  "hr",
  "html",
  "i",
  "iframe",
  "img",
  "input",
  "ins",
  "kbd",
  "label",
  "legend",
  "li",
  "link",
  "main",
  "map",
  "mark",
  "menu",
  "meta",
  "meter",
  "nav",
  "noscript",
  "object",
  "ol",
  "optgroup",
  "option",
  "output",
  "p",
  "picture",
  "pre",
  "progress",
  "q",
  "rp",
  "rt",
  "ruby",
  "s",
  "samp",
  "script",
  "search",
  "section",
  "select",
  "slot",
  "small",
  "source",
  "span",
  "strong",
  "style",
  "sub",
  "summary",
  "sup",
  "table",
  "tbody",
  "td",
  "template",
  "textarea",
  "tfoot",
  "th",
  "thead",
  "time",
  "title",
  "tr",
  "track",
  "u",
  "ul",
  "var",
  "video",
  "wbr"
];

const CORE_TAGS: TagEntry[] = [
  {
    key: "display_grid",
    label: "display: grid",
    category: "css",
    tutorial: "Cria layout por linhas e colunas com responsividade forte.",
    example:
      ".cards { display:grid; grid-template-columns:repeat(auto-fit,minmax(220px,1fr)); gap:16px; }",
    aliases: ["grid", "css grid"]
  },
  {
    key: "media_query",
    label: "@media",
    category: "css",
    tutorial: "Aplica regras diferentes para cada tamanho de tela.",
    example: "@media (max-width: 768px) { .sidebar { display:none; } }",
    aliases: ["responsive", "breakpoint"]
  },
  {
    key: "fetch_api",
    label: "fetch API",
    category: "javascript",
    tutorial: "Faz chamadas HTTP para APIs e trata resposta.",
    example: "const res = await fetch('/api/data'); const json = await res.json();",
    aliases: ["fetch", "api"]
  },
  {
    key: "use_state",
    label: "useState",
    category: "react",
    tutorial: "Controla estado local em componentes React.",
    example: "const [open, setOpen] = useState(false);",
    aliases: ["state", "hook"]
  },
  {
    key: "use_effect",
    label: "useEffect",
    category: "react",
    tutorial: "Executa efeitos colaterais como fetch e listeners.",
    example: "useEffect(() => { carregarDados(); }, []);",
    aliases: ["effect", "hook"]
  },
  {
    key: "express_route",
    label: "Express route",
    category: "node",
    tutorial: "Define endpoint HTTP no backend Node/Express.",
    example: "app.post('/api/users', async (req, res) => { res.json({ ok:true }); });",
    aliases: ["route", "express"]
  },
  {
    key: "jwt_auth",
    label: "JWT auth",
    category: "node",
    tutorial: "Autenticacao por token assinado com expiracao.",
    example: "const token = jwt.sign({ userId }, SECRET, { expiresIn: '1d' });",
    aliases: ["jwt", "auth"]
  },
  {
    key: "aida",
    label: "AIDA",
    category: "marketing",
    tutorial: "Copy em quatro fases: Atencao, Interesse, Desejo e Acao.",
    example:
      "Atencao: headline forte | Interesse: dor real | Desejo: beneficios | Acao: CTA objetivo.",
    aliases: ["copy", "vendas"]
  },
  {
    key: "pas",
    label: "PAS",
    category: "marketing",
    tutorial: "Copy de conversao: Problema, Agitacao e Solucao.",
    example:
      "Problema: queda de vendas | Agitacao: perda de caixa | Solucao: automacao com IA.",
    aliases: ["copy", "framework"]
  },
  {
    key: "cta",
    label: "CTA",
    category: "marketing",
    tutorial: "Chamada para acao direta e clara.",
    example: "Clique agora e gere sua primeira versao em 5 minutos.",
    aliases: ["call to action", "botao"]
  },
  {
    key: "seo_title",
    label: "SEO title",
    category: "marketing",
    tutorial: "Titulo focado em palavra-chave e intencao de busca.",
    example: "<title>Curso de React para Iniciantes | Guia Completo</title>",
    aliases: ["seo", "title"]
  },
  {
    key: "schema_json_ld",
    label: "schema JSON-LD",
    category: "seo",
    tutorial: "Dados estruturados para melhorar entendimento no Google.",
    example:
      "<script type='application/ld+json'>{\"@context\":\"https://schema.org\",\"@type\":\"Article\"}</script>",
    aliases: ["schema", "json-ld"]
  }
];

function createHtmlTagEntry(tag: string): TagEntry {
  const voidTag = VOID_HTML_TAGS.has(tag);
  const label = `<${tag}>`;
  const example = voidTag
    ? `<${tag} />`
    : `<${tag}>Conteudo de exemplo</${tag}>`;

  return {
    key: `html_${tag}`,
    label,
    category: "html",
    tutorial: `A tag ${label} e um elemento HTML usado na estrutura da pagina.`,
    example,
    aliases: [tag, `tag ${tag}`]
  };
}

const htmlEntries = HTML_TAGS.map(createHtmlTagEntry);

const map = new Map<string, TagEntry>();
for (const tag of [...CORE_TAGS, ...htmlEntries]) {
  map.set(tag.key, tag);
}

export const WORLD_TAGS: TagEntry[] = Array.from(map.values()).sort((a, b) =>
  a.label.localeCompare(b.label)
);

export function normalizeSearch(value: string) {
  return slugify(value).replace(/_/g, " ");
}

